language: csharp
solution: hw-dotnetcore.sln
mono: none
dotnet: 1.0.3
dist: trusty
script:
 - dotnet clean src/src.csproj
 - dotnet restore src/src.csproj
 - dotnet restore test/test.csproj
 - dotnet test test/test.csproj
 - dotnet publish -c Release src/src.csproj