language: csharp
solution: hw-dotnetcore.sln
mono: none
dotnet: 1.0.3
dist: trusty
services:
 - docker
script:
 - dotnet clean src/src.csproj
 - dotnet restore src/src.csproj
 - dotnet restore test/test.csproj
 - dotnet test test/test.csproj
 - docker build -t hw-helloworld:`echo $TRAVIS_BUILD_NUMBER`` src/